apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: docker.io/httpd
    name: test-container
    volumeMounts:
    - mountPath: /simplilearn
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /cka
      # this field is optional
      type: DirectoryOrCreate

