apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: t3
  name: t3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: t3
    spec:
      containers:
      - image: docker.io/nginx
        name: nginx
        resources: {}
status: {}
