apiVersion: networking.k8s.io/v1beta1  ### if it is v1.13 you can use extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /testpath2
        backend:
          serviceName: myapp1
          servicePort: 80
      - path: /testpath3
        backend:
          serviceName: myapp2
          servicePort: 8080

