apiVersion: v1
kind: Pod
metadata:
  name: mc2
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: 1st
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /html-demo1
  - name: 2nd
    image: debian
    volumeMounts:
    - name: html
      mountPath: /html-demo2
